/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "09_like.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_09_like(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, " create filter function \"like\"(val string, pat string, esc string) external name algebra.\"like\"; create filter function \"ilike\"(val string, pat string, esc string) external name algebra.\"ilike\"; create filter function \"like\"(val string, pat string) external name algebra.\"like\"; create filter function \"ilike\"(val string, pat string) external name algebra.\"ilike\"; grant execute on filter function \"like\" (string, string, string) to public; grant execute on filter function \"ilike\" (string, string, string) to public; grant execute on filter function \"like\" (string, string) to public; grant execute on filter function \"ilike\" (string, string) to public;");
	if (pos >= bufsize)
		throw(SQL, "createdb.09_like", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 09_like.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.09_like", 1, 0, NULL);
}
