/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "13_date.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_13_date(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, " create function str_to_date(s string, format string) returns date external name mtime.\"str_to_date\"; create function date_to_str(d date, format string) returns string external name mtime.\"date_to_str\"; create function str_to_time(s string, format string) returns time external name mtime.\"str_to_time\"; create function time_to_str(d time, format string) returns string external name mtime.\"time_to_str\"; create function str_to_timestamp(s string, format string) returns timestamp external name mtime.\"str_to_timestamp\"; create function timestamp_to_str(d timestamp, format string) returns string external name mtime.\"timestamp_to_str\"; grant execute on function str_to_date to public; grant execute on function date_to_str to public; grant execute on function str_to_time to public; grant execute on function time_to_str to public; grant execute on function str_to_timestamp to public; grant execute on function timestamp_to_str to public;");
	if (pos >= bufsize)
		throw(SQL, "createdb.13_date", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 13_date.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.13_date", 1, 0, NULL);
}
