/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "13_date", "\ncreate function str_to_date(s string, format string) returns date\nexternal name mtime.\"str_to_date\";\ncreate function date_to_str(d date, format string) returns string\nexternal name mtime.\"date_to_str\";\ncreate function str_to_time(s string, format string) returns time\nexternal name mtime.\"str_to_time\";\ncreate function time_to_str(d time, format string) returns string\nexternal name mtime.\"time_to_str\";\ncreate function str_to_timestamp(s string, format string) returns timestamp\nexternal name mtime.\"str_to_timestamp\";\ncreate function timestamp_to_str(d timestamp, format string) returns string\nexternal name mtime.\"timestamp_to_str\";\ngrant execute on function str_to_date to public;\ngrant execute on function date_to_str to public;\ngrant execute on function str_to_time to public;\ngrant execute on function time_to_str to public;\ngrant execute on function str_to_timestamp to public;\ngrant execute on function timestamp_to_str to public;" }, 
