/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "15_querylog", "\n\ncreate function sys.querylog_catalog()\nreturns table(\nid oid,\nowner string,\ndefined timestamp,\nquery string,\npipe string,\n\"plan\" string,\t\tmal int,\t\toptimize bigint\t)\nexternal name sql.querylog_catalog;\n\ncreate function sys.querylog_calls()\nreturns table(\nid oid,\t\t\"start\" timestamp,\t\t\"stop\" timestamp,\t\targuments string,\t\ttuples bigint,\t\trun bigint,\t\tship bigint,\t\tcpu int,\t\tio int\t)\nexternal name sql.querylog_calls;\ncreate view sys.querylog_catalog as select * from sys.querylog_catalog();\ncreate view sys.querylog_calls as select * from sys.querylog_calls();\ncreate view sys.querylog_history as\nselect qd.*, ql.\"start\",ql.\"stop\", ql.arguments, ql.tuples, ql.run, ql.ship, ql.cpu, ql.io\nfrom sys.querylog_catalog() qd, sys.querylog_calls() ql\nwhere qd.id = ql.id and qd.owner = user;\ncreate procedure sys.querylog_empty()\nexternal name sql.querylog_empty;\ncreate procedure sys.querylog_enable()\nexternal name sql.querylog_enable;\ncreate procedure sys.querylog_enable(threshold smallint)\nexternal name sql.querylog_enable_threshold;\ncreate procedure sys.querylog_disable()\nexternal name sql.querylog_disable;" }, 
