/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "16_tracelog.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_16_tracelog(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, " create function sys.tracelog() returns table ( event integer,		clk varchar(20),		pc varchar(50),		thread int,		ticks bigint,		rrsMB bigint,		vmMB bigint,		reads bigint,		writes bigint,		minflt bigint,		majflt bigint,		nvcsw bigint,		stmt string		) external name sql.dump_trace; create view sys.tracelog as select * from sys.tracelog();");
	if (pos >= bufsize)
		throw(SQL, "createdb.16_tracelog", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 16_tracelog.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.16_tracelog", 1, 0, NULL);
}
