/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "16_tracelog", " create function sys.tracelog() returns table ( event integer,		clk varchar(20),		pc varchar(50),		thread int,		ticks bigint,		rrsMB bigint,		vmMB bigint,		reads bigint,		writes bigint,		minflt bigint,		majflt bigint,		nvcsw bigint,		stmt string		) external name sql.dump_trace; create view sys.tracelog as select * from sys.tracelog();" }, 
