/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "16_tracelog", "\ncreate function sys.tracelog()\nreturns table (\nevent integer,\t\tclk varchar(20),\t\tpc varchar(50),\t\tthread int,\t\tticks bigint,\t\trrsMB bigint,\t\tvmMB bigint,\t\treads bigint,\t\twrites bigint,\t\tminflt bigint,\t\tmajflt bigint,\t\tnvcsw bigint,\t\tstmt string\t\t)\nexternal name sql.dump_trace;\ncreate view sys.tracelog as select * from sys.tracelog();" }, 
