/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "17_temporal", "\ncreate function sys.\"epoch\"(sec BIGINT) returns TIMESTAMP\nexternal name timestamp.\"epoch\";\ncreate function sys.\"epoch\"(sec INT) returns TIMESTAMP\nexternal name timestamp.\"epoch\";\ncreate function sys.\"epoch\"(ts TIMESTAMP) returns INT\nexternal name timestamp.\"epoch\";\ncreate function sys.\"epoch\"(ts TIMESTAMP WITH TIME ZONE) returns INT\nexternal name timestamp.\"epoch\";\ngrant execute on function sys.\"epoch\" (BIGINT) to public;\ngrant execute on function sys.\"epoch\" (INT) to public;\ngrant execute on function sys.\"epoch\" (TIMESTAMP) to public;\ngrant execute on function sys.\"epoch\" (TIMESTAMP WITH TIME ZONE) to public;" }, 
