/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "20_vacuum", "\n\n\ncreate procedure shrink(sys string, tab string)\nexternal name sql.shrink;\ncreate procedure reuse(sys string, tab string)\nexternal name sql.reuse;\ncreate procedure vacuum(sys string, tab string)\nexternal name sql.vacuum;\n" }, 
