/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "22_clients", "\ncreate function sys.password_hash (username string)\nreturns string\nexternal name sql.password;\ncreate function sys.remote_table_credentials (tablename string)\nreturns table (\"uri\" string, \"username\" string, \"hash\" string)\nexternal name sql.rt_credentials;\ncreate function sys.sessions()\nreturns table(\"user\" string, \"login\" timestamp, \"sessiontimeout\" bigint, \"lastcommand\" timestamp, \"querytimeout\" bigint, \"active\" bool)\nexternal name sql.sessions;\ncreate view sys.sessions as select * from sys.sessions();\ncreate procedure sys.shutdown(delay tinyint)\nexternal name sql.shutdown;\ncreate procedure sys.shutdown(delay tinyint, force bool)\nexternal name sql.shutdown;\ncreate procedure sys.settimeout(\"query\" bigint)\nexternal name clients.settimeout;\ncreate procedure sys.settimeout(\"query\" bigint, \"session\" bigint)\nexternal name clients.settimeout;\ncreate procedure sys.setsession(\"timeout\" bigint)\nexternal name clients.setsession;" }, 
