/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "23_skyserver", "\nCREATE FUNCTION MS_STUFF( s1 varchar(32), st int, len int, s3 varchar(32))\nRETURNS varchar(32)\nBEGIN\nDECLARE res varchar(32), aux varchar(32);\nDECLARE ofset int;\nIF ( st < 0 or st > LENGTH(s1))\nTHEN RETURN '';\nEND IF;\nSET ofset = 1;\nSET res = SUBSTRING(s1,ofset,st-1);\nSET res = res || s3;\nSET ofset = st + len;\nSET aux = SUBSTRING(s1,ofset,LENGTH(s1)-ofset+1);\nSET res = res || aux;\nRETURN res;\nEND;\ngrant execute on function MS_STUFF to public;\nCREATE FUNCTION MS_TRUNC(num double, prc int)\nRETURNS double\nexternal name sql.ms_trunc;\ngrant execute on function MS_TRUNC to public;\nCREATE FUNCTION MS_ROUND(num double, prc int, truncat int)\nRETURNS double\nBEGIN\nIF (truncat = 0)\nTHEN RETURN ROUND(num, prc);\nELSE RETURN MS_TRUNC(num, prc);\nEND IF;\nEND;\ngrant execute on function MS_ROUND to public;\nCREATE FUNCTION MS_STR(num float, prc int, truncat int)\nRETURNS string\nBEGIN\nRETURN CAST(num as string);\nEND;\ngrant execute on function MS_STR to public;\nCREATE FUNCTION alpha(pdec double, pradius double)\nRETURNS double EXTERNAL NAME sql.alpha;\ngrant execute on function alpha to public;" }, 
