/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "25_debug", "\ncreate function sys.optimizer_stats()\nreturns table (optname string, count int, timing bigint)\nexternal name inspect.optimizer_stats;\n\ncreate function sys.queryCache()\nreturns table (query string, count int)\nexternal name sql.dump_cache;\ncreate procedure sys.querylog(filename string)\nexternal name sql.logfile;\ncreate function sys.optimizers ()\nreturns table (name string, def string, status string)\nexternal name sql.optimizers;\ncreate view sys.optimizers as select * from sys.optimizers();\ncreate view sys.environment as select * from sys.env();\nGRANT SELECT ON sys.environment TO PUBLIC;\ncreate function sys.bbp ()\nreturns table (id int, name string,\nttype string, count BIGINT, refcnt int, lrefcnt int,\nlocation string, heat int, dirty string,\nstatus string, kind string)\nexternal name bbp.get;\ncreate function sys.malfunctions()\nreturns table(\"module\" string, \"function\" string, \"signature\" string, \"address\" string, \"comment\" string)\nexternal name \"manual\".\"functions\";\ncreate procedure sys.evalAlgebra( ra_stmt string, opt bool)\nexternal name sql.\"evalAlgebra\";\ncreate procedure sys.flush_log ()\nexternal name sql.\"flush_log\";\ncreate function sys.debug(debug int) returns integer\nexternal name mdb.\"setDebug\";" }, 
