/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "26_sysmon.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_26_sysmon(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, "  create function sys.queue() returns table( qtag bigint, \"user\" string, started timestamp, estimate timestamp, progress int, status string, tag oid, query string ) external name sql.sysmon_queue; create view sys.queue as select * from sys.queue(); create procedure sys.pause(tag int) external name sql.sysmon_pause; create procedure sys.resume(tag int) external name sql.sysmon_resume; create procedure sys.stop(tag int) external name sql.sysmon_stop; create procedure sys.pause(tag bigint) external name sql.sysmon_pause; create procedure sys.resume(tag bigint) external name sql.sysmon_resume; create procedure sys.stop(tag bigint) external name sql.sysmon_stop;");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 26_sysmon.sql\n");
	return SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
}
