/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "26_sysmon", "\n\ncreate function sys.queue()\nreturns table(\nqtag bigint,\n\"user\" string,\nstarted timestamp,\nestimate timestamp,\nprogress int,\nstatus string,\ntag oid,\nquery string\n)\nexternal name sql.sysmon_queue;\ncreate view sys.queue as select * from sys.queue();\ncreate procedure sys.pause(tag int)\nexternal name sql.sysmon_pause;\ncreate procedure sys.resume(tag int)\nexternal name sql.sysmon_resume;\ncreate procedure sys.stop(tag int)\nexternal name sql.sysmon_stop;\ncreate procedure sys.pause(tag bigint)\nexternal name sql.sysmon_pause;\ncreate procedure sys.resume(tag bigint)\nexternal name sql.sysmon_resume;\ncreate procedure sys.stop(tag bigint)\nexternal name sql.sysmon_stop;" }, 
