/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "27_rejects", "\n\ncreate function sys.rejects()\nreturns table(\nrowid bigint,\nfldid int,\n\"message\" string,\n\"input\" string\n)\nexternal name sql.copy_rejects;\ngrant execute on function rejects to public;\ncreate view sys.rejects as select * from sys.rejects();\ncreate procedure sys.clearrejects()\nexternal name sql.copy_rejects_clear;" }, 
