/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "39_analytics_hge", "\ncreate aggregate stddev_samp(val HUGEINT) returns DOUBLE\nexternal name \"aggr\".\"stdev\";\nGRANT EXECUTE ON AGGREGATE stddev_samp(HUGEINT) TO PUBLIC;\ncreate aggregate stddev_pop(val HUGEINT) returns DOUBLE\nexternal name \"aggr\".\"stdevp\";\nGRANT EXECUTE ON AGGREGATE stddev_pop(HUGEINT) TO PUBLIC;\ncreate aggregate var_samp(val HUGEINT) returns DOUBLE\nexternal name \"aggr\".\"variance\";\nGRANT EXECUTE ON AGGREGATE var_samp(HUGEINT) TO PUBLIC;\ncreate aggregate var_pop(val HUGEINT) returns DOUBLE\nexternal name \"aggr\".\"variancep\";\nGRANT EXECUTE ON AGGREGATE var_pop(HUGEINT) TO PUBLIC;\ncreate aggregate median(val HUGEINT) returns HUGEINT\nexternal name \"aggr\".\"median\";\nGRANT EXECUTE ON AGGREGATE median(HUGEINT) TO PUBLIC;\ncreate aggregate quantile(val HUGEINT, q DOUBLE) returns HUGEINT\nexternal name \"aggr\".\"quantile\";\nGRANT EXECUTE ON AGGREGATE quantile(HUGEINT, DOUBLE) TO PUBLIC;\ncreate aggregate corr(e1 HUGEINT, e2 HUGEINT) returns DOUBLE\nexternal name \"aggr\".\"corr\";\nGRANT EXECUTE ON AGGREGATE corr(HUGEINT, HUGEINT) TO PUBLIC;" }, 
