/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "41_md5sum.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_41_md5sum(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, "  create function sys.md5(v string) returns string external name clients.md5sum; grant execute on function md5 to public;");
	if (pos >= bufsize)
		throw(SQL, "createdb.41_md5sum", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 41_md5sum.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.41_md5sum", 1, 0, NULL);
}
