/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "45_uuid.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_45_uuid(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, "  create type uuid external name uuid; create function sys.uuid() returns uuid external name uuid.\"new\"; GRANT EXECUTE ON FUNCTION sys.uuid() TO PUBLIC; create function sys.isaUUID(s string) returns boolean external name uuid.\"isaUUID\"; GRANT EXECUTE ON FUNCTION sys.isaUUID(string) TO PUBLIC;");
	if (pos >= bufsize)
		throw(SQL, "createdb.45_uuid", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 45_uuid.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.45_uuid", 1, 0, NULL);
}
