/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "45_uuid", "\n\ncreate type uuid external name uuid;\ncreate function sys.uuid()\nreturns uuid external name uuid.\"new\";\nGRANT EXECUTE ON FUNCTION sys.uuid() TO PUBLIC;\ncreate function sys.isaUUID(s string)\nreturns boolean external name uuid.\"isaUUID\";\nGRANT EXECUTE ON FUNCTION sys.isaUUID(string) TO PUBLIC;" }, 
