/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "46_profiler", "\ncreate schema profiler;\ncreate procedure profiler.start() external name profiler.\"start\";\ncreate procedure profiler.stop() external name profiler.stop;\ncreate procedure profiler.setheartbeat(beat int) external name profiler.setheartbeat;\ncreate function profiler.getlimit() returns integer external name profiler.getlimit;\ncreate procedure profiler.setlimit(lim integer) external name profiler.setlimit;" }, 
