/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "60_wlcr", "\n\ncreate procedure master()\nexternal name wlc.master;\ncreate procedure master(path string)\nexternal name wlc.master;\ncreate procedure stopmaster()\nexternal name wlc.stopmaster;\ncreate procedure masterbeat( duration int)\nexternal name wlc.\"setmasterbeat\";\ncreate function masterClock() returns string\nexternal name wlc.\"getmasterclock\";\ncreate function masterTick() returns bigint\nexternal name wlc.\"getmastertick\";\ncreate procedure replicate()\nexternal name wlr.replicate;\ncreate procedure replicate(pointintime timestamp)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string, pointintime timestamp)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string, id tinyint)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string, id smallint)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string, id integer)\nexternal name wlr.replicate;\ncreate procedure replicate(dbname string, id bigint)\nexternal name wlr.replicate;\ncreate procedure replicabeat(duration integer)\nexternal name wlr.\"setreplicabeat\";\ncreate function replicaClock() returns string\nexternal name wlr.\"getreplicaclock\";\ncreate function replicaTick() returns bigint\nexternal name wlr.\"getreplicatick\";\n" }, 
