/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "80_statistics", "\n\nCREATE TABLE sys.statistics(\n\"column_id\" integer,\n\"type\" string,\nwidth integer,\nstamp timestamp,\n\"sample\" bigint,\n\"count\" bigint,\n\"unique\" bigint,\n\"nils\" bigint,\nminval string,\nmaxval string,\nsorted boolean,\nrevsorted boolean);\ncreate procedure sys.analyze(minmax int, \"sample\" bigint)\nexternal name sql.analyze;\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string)\nexternal name sql.analyze;\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string)\nexternal name sql.analyze;\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string, col string)\nexternal name sql.analyze;" }, 
