/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "71_statistics", "\n\n\nCREATE TABLE sys.statistics(\n\t\"column_id\" integer,\n\t\"type\" string,\n\twidth integer,\n\tstamp timestamp,\n\t\"sample\" bigint,\n\t\"count\" bigint,\n\t\"unique\" bigint,\n\t\"nils\" bigint,\n\tminval string,\n\tmaxval string,\n\tsorted boolean,\n\trevsorted boolean);\n\ncreate procedure sys.analyze(minmax int, \"sample\" bigint)\nexternal name sql.analyze;\n\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string)\nexternal name sql.analyze;\n\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string)\nexternal name sql.analyze;\n\ncreate procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string, col string)\nexternal name sql.analyze;" }, 
