/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "72_fits", "\ncreate procedure listdir(dirname string) external name fits.listdir;\ncreate procedure fitsattach(fname string) external name fits.attach;\ncreate procedure fitsload(tname string) external name fits.load;\ncreate procedure listdirpat(dirname string,pat string) external name fits.listdirpattern;" }, 
