/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "74_netcdf", "\ncreate table netcdf_files(\nfile_id int,\nlocation char(256));\n\ncreate table netcdf_dims(\ndim_id int,\nfile_id int,\nname varchar(64),\nlength int);\ncreate table netcdf_vars(\nvar_id int,\nfile_id int,\nname varchar(64),\nvartype varchar(64),\nndim int,\ncoord_dim_id int);\n\ncreate table netcdf_vardim(\nvar_id int,\ndim_id int,\nfile_id int,\ndimpos int);\ncreate table netcdf_attrs(\nobj_name varchar(256),\natt_name varchar(256),\natt_type varchar(64),\nvalue text,\nfile_id int,\ngr_name varchar(256));\n\n\ncreate procedure netcdf_attach(fname varchar(256))\nexternal name netcdf.attach;\ncreate procedure netcdf_importvar(fid integer, varnname varchar(256))\nexternal name netcdf.importvariable;\ngrant select on netcdf_files to public;\ngrant select on netcdf_dims to public;\ngrant select on netcdf_vars to public;\ngrant select on netcdf_vardim to public;\ngrant select on netcdf_attrs to public;\ngrant execute on procedure netcdf_attach(varchar(256)) to public;\ngrant execute on procedure netcdf_importvar(integer, varchar(256)) to public;" }, 
