/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "74_netcdf", " create table netcdf_files( file_id int, location char(256));  create table netcdf_dims( dim_id int, file_id int, name varchar(64), length int); create table netcdf_vars( var_id int, file_id int, name varchar(64), vartype varchar(64), ndim int, coord_dim_id int);  create table netcdf_vardim( var_id int, dim_id int, file_id int, dimpos int); create table netcdf_attrs( obj_name varchar(256), att_name varchar(256), att_type varchar(64), value text, file_id int, gr_name varchar(256));   create procedure netcdf_attach(fname varchar(256)) external name netcdf.attach; create procedure netcdf_importvar(fid integer, varnname varchar(256)) external name netcdf.importvariable; grant select on netcdf_files to public; grant select on netcdf_dims to public; grant select on netcdf_vars to public; grant select on netcdf_vardim to public; grant select on netcdf_attrs to public; grant execute on procedure netcdf_attach(varchar(256)) to public; grant execute on procedure netcdf_importvar(integer, varchar(256)) to public;" }, 
