/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "80_statistics.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_80_statistics(Client c, char *buf, size_t bufsize)
{
	size_t pos = 0;

	pos += snprintf(buf, bufsize, "  CREATE TABLE sys.statistics( \"column_id\" integer, \"type\" string, width integer, stamp timestamp, \"sample\" bigint, \"count\" bigint, \"unique\" bigint, \"nils\" bigint, minval string, maxval string, sorted boolean, revsorted boolean); create procedure sys.analyze(minmax int, \"sample\" bigint) external name sql.analyze; create procedure sys.analyze(minmax int, \"sample\" bigint, sch string) external name sql.analyze; create procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string) external name sql.analyze; create procedure sys.analyze(minmax int, \"sample\" bigint, sch string, tbl string, col string) external name sql.analyze;");
	if (pos >= bufsize)
		throw(SQL, "createdb.80_statistics", SQLSTATE(42000) "SQL script to install is too large");
	printf("# loading sql script: 80_statistics.sql\n");
	return SQLstatementIntern(c, &buf, "createdb.80_statistics", 1, 0, NULL);
}
