/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "81_udf", "  create function reverse(src string) returns string external name udf.reverse; create function fuse(one tinyint, two tinyint) returns smallint external name udf.fuse; create function fuse(one smallint, two smallint) returns integer external name udf.fuse; create function fuse(one integer, two integer) returns bigint external name udf.fuse;" }, 
