/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with sql2h.py. Do not edit this file directly.
{ "99_system", "\ncreate trigger system_update_schemas after update on sys.schemas for each statement call sys_update_schemas();\ncreate trigger system_update_tables after update on sys._tables for each statement call sys_update_tables();\nupdate sys.functions set system = true;\ncreate view sys.systemfunctions as select id as function_id from sys.functions where system;\ngrant select on sys.systemfunctions to public;\nupdate sys._tables set system = true;\nupdate sys.schemas set system = true;\nUPDATE sys.types SET schema_id = (SELECT id FROM sys.schemas WHERE name = 'sys') WHERE schema_id = 0 AND schema_id NOT IN (SELECT id from sys.schemas);\nUPDATE sys.functions SET schema_id = (SELECT id FROM sys.schemas WHERE name = 'sys') WHERE schema_id = 0 AND schema_id NOT IN (SELECT id from sys.schemas);" }, 
