/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "alarm", "\nmodule alarm;\n\nunsafe command alarm.sleep(secs:int):void\naddress ALARMsleep\ncomment \"Sleep a few seconds\";\n\nunsafe command alarm.usec() :lng\naddress ALARMusec\ncomment \"Return time in microseconds.\";\n\nunsafe command alarm.time() :int\naddress ALARMtime\ncomment \"Return time in milliseconds.\";\n\nunsafe command alarm.epoch() :int\naddress ALARMepoch\ncomment \"Return the current time as UNIX epoch.\";\n\nunsafe command alarm.ctime() :str\naddress ALARMctime\ncomment \"Return the current time as a C-time string.\";\n" }, 
