/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "logger", "\nmodule logger;\n\natom logger = ptr;\nend;\ncommand create( debug:int, fn:str, dirname:str, version:int ):logger\naddress logger_create_wrap\ncomment \"Create logger, check if recovery is needed. The fn variable names the frontend,this is needed to keep the catalog bat seperate\";\n\ncommand destroy( l:logger ) :void\naddress logger_destroy_wrap\ncomment \"Free the resources used by the logger.\";\n" }, 
