/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "status", "\nmodule status;\n\ncommand cpuStatistics()(:bat[:str],:bat[:lng] )\naddress SYScpuStatistics\n;\ncommand memStatistics() (:bat[:str],:bat[:lng] )\naddress SYSmemStatistics\n;\ncommand ioStatistics()(:bat[:str],:bat[:lng] )\naddress SYSioStatistics\n;\ncommand vmStatistics(minsize:lng)(:bat[:str],:bat[:lng] )\naddress SYSvm_usage\n;\ncommand memUsage(minsize:lng)(:bat[:str],:bat[:lng] )\naddress SYSmem_usage\n;\n\ncommand batStatistics()(:bat[:str],:bat[:str] )\naddress SYSgdkEnv\n;\ncommand getThreads()(:bat[:int],:bat[:str] )\naddress SYSgdkThread\n;\n\ncommand mem_cursize():lng \naddress SYSgetmem_cursize\n;\n\ncommand mem_maxsize():lng \naddress SYSgetmem_maxsize\n;\n\ncommand mem_maxsize(v:lng):void \naddress SYSsetmem_maxsize\n;\n\ncommand vm_cursize():lng \naddress SYSgetvm_cursize\n;\n\ncommand vm_maxsize():lng \naddress SYSgetvm_maxsize\n;\n\ncommand vm_maxsize(v:lng):void \naddress SYSsetvm_maxsize\n;" }, 
