# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

# This file was generated by using the script 41_grid_hge.sql.sh.

CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 TINYINT, y2 TINYINT, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 SMALLINT, y2 SMALLINT, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 INTEGER, y2 INTEGER, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 BIGINT, y2 BIGINT, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 DECIMAL, y2 DECIMAL, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 HUGEINT, y2 HUGEINT, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 REAL, y2 REAL, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
CREATE FILTER FUNCTION distance(x1 HUGEINT, y1 HUGEINT, x2 DOUBLE, y2 DOUBLE, distance DOUBLE) EXTERNAL NAME grid_hge.distance;

