# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

sed '/^$/q' $0			# copy copyright from this file

cat <<EOF
# This file was generated by using the script ${0##*/}.

EOF

integer="TINYINT SMALLINT INTEGER BIGINT DECIMAL HUGEINT"	# all integer types
numeric="$integer REAL DOUBLE"	# all numeric types

name="distance"
for tp1 in "HUGEINT"; do
	for tp2 in $numeric; do
	    cat <<EOF
CREATE FILTER FUNCTION distance(x1 ${tp1}, y1 ${tp1}, x2 ${tp2}, y2 ${tp2}, distance DOUBLE) EXTERNAL NAME grid_hge.distance;
EOF
	done
done
echo
