# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 40_geom.sql
}

headers_sql_grid = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 41_grid.sql
}

headers_sql_grid_hge = {
	COND = HAVE_HGE
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 41_grid_hge.sql
}

EXTRA_DIST_DIR = Tests
