/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "00_mal_mapi_hge", "\nmodule mapi;\n\ncommand fetch_field(hdl:int,fnr:int):hge\naddress SERVERfetch_field_hge\ncomment \"Retrieve a single hge field.\";" }, 
