/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "bbp", "\nmodule bbp;\n\npattern bind(name:str):bat[:any_2]\naddress CMDbbpbind\n;\n\ncommand getIndex(b:bat[:any_2]):int\naddress CMDbbpgetIndex\n;\n\ncommand getNames() :bat[:str] \t\naddress CMDbbpNames\n;\n\ncommand get() (id:bat[:int], \n\t\t\tns:bat[:str],\n\t       tt:bat[:str],\n\t       cnt:bat[:lng], refcnt:bat[:int],\n\t       lrefcnt:bat[:int], location:bat[:str],\n\t       heat:bat[:int], dirty:bat[:str],\n\t       status:bat[:str], kind:bat[:str])\naddress CMDbbp\n;\n\ncommand getName( b:bat[:any_1]):str\naddress CMDbbpName\n;\ncommand setName( b:bat[:any_1], n:str):str\naddress CMDsetName\n;\ncommand getCount() :bat[:lng] \t\naddress CMDbbpCount\n;\ncommand getRefCount() :bat[:int] \t\naddress CMDbbpRefCount\n;\ncommand getLRefCount() :bat[:int] \t\naddress CMDbbpLRefCount\n;\ncommand getLocation() :bat[:str] \t\naddress CMDbbpLocation\n;\ncommand getDirty() :bat[:str] \t\naddress CMDbbpDirty\n;\ncommand getStatus() :bat[:str] \t\naddress CMDbbpStatus\n;\ncommand getKind():bat[:str] \naddress CMDbbpKind\n;\ncommand getRefCount(b:bat[:any_1]) :int\naddress CMDgetBATrefcnt\n;\ncommand getLRefCount(b:bat[:any_1]) :int\naddress CMDgetBATlrefcnt\n;\ncommand getDiskSpace() :lng\naddress CMDbbpDiskSpace\n;\ncommand getPageSize():int\naddress CMDgetPageSize\n;" }, 
