/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "factories", "\nmodule factories;\n\ncommand getPlants()(mod:bat[:str], fcn:bat[:str])\naddress FCTgetPlants \ncomment \"Retrieve the names for all active factories.\";\n\ncommand getCaller():int\naddress FCTgetCaller\ncomment \"Retrieve the unique identity of the factory caller.\";\n\ncommand getOwners():bat[:str]\naddress FCTgetOwners\ncomment \"Retrieve the factory owners table.\";\n\ncommand getArrival():bat[:timestamp]\naddress FCTgetArrival\ncomment \"Retrieve the time stamp the last call was made.\";\n\ncommand getDeparture():bat[:timestamp]\naddress FCTgetDeparture\ncomment \"Retrieve the time stamp the last answer was returned.\";\n\npattern shutdown(m:str, f:str):void\naddress FCTshutdown\ncomment \"Close a factory.\";" }, 
