/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "inspect", "\nmodule inspect;\n\npattern getDefinition(mod:str,fcn:str) :bat[:str] \naddress INSPECTgetDefinition\n;\n\npattern getSignature(mod:str,fcn:str) :bat[:str] \naddress INSPECTgetSignature\n;\n\npattern getAddress(mod:str,fcn:str) :bat[:str] \naddress INSPECTgetAddress\n;\n\npattern getComment(mod:str,fcn:str) :bat[:str]\naddress INSPECTgetComment\n;\n\npattern getSource(mod:str,fcn:str):str\naddress INSPECTgetSource\n;\n\npattern getKind():bat[:str]\naddress INSPECTgetkind\n;\npattern getModule():bat[:str]\naddress INSPECTgetAllModules\n;\npattern getFunction():bat[:str]\naddress INSPECTgetAllFunctions\n;\npattern getSignatures():bat[:str]\naddress INSPECTgetAllSignatures\n;\npattern getAddresses():bat[:str]\naddress INSPECTgetAllAddresses\n;\n\n\npattern getSize():lng\naddress INSPECTgetSize\n;\n\npattern getSize(mod:str,fcn:str):lng\naddress INSPECTgetFunctionSize\n;\n\n\npattern getType(v:any_1) :str \naddress INSPECTtypeName\n;\n\npattern equalType(l:any, r:any):bit\naddress INSPECTequalType\n;\ncommand getAtomNames():bat[:str] \naddress INSPECTatom_names\n;\ncommand getAtomSuper():bat[:str] \naddress INSPECTatom_sup_names\n;\ncommand getAtomSizes():bat[:int] \naddress INSPECTatom_sizes\n;\n\ncommand getEnvironment() (k:bat[:str], v:bat[:str])\naddress INSPECTgetEnvironment\n;\ncommand getEnvironment(k:str) :str\naddress INSPECTgetEnvironmentKey\n;" }, 
