/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "iterator", "\nmodule iterator;\n\ncommand new(b:bat[:any_2], size:lng) (:lng,:bat[:any_2])\naddress ITRnewChunk\n;\n\ncommand next(b:bat[:any_2], size:lng) (:lng, :bat[:any_2])\naddress ITRnextChunk\n;\n\npattern new(b:bat[:any_2]) (h:oid, t:any_2)\naddress ITRbunIterator\n;\n\npattern next(b:bat[:any_2]) (h:oid, t:any_2)\naddress ITRbunNext\n;\n\ncommand next(step:oid,last:oid):oid\naddress ITRnext_oid; \ncommand next(step:sht,last:sht):sht\naddress ITRnext_sht; \ncommand next(step:int,last:int):int\naddress ITRnext_int; \ncommand next(step:lng,last:lng):lng\naddress ITRnext_lng; \ncommand next(step:flt,last:flt):flt\naddress ITRnext_flt; \ncommand next(step:dbl,last:dbl):dbl\naddress ITRnext_dbl \n;" }, 
