/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "json_util", "\n\nmodule json;\n\ncommand resultSet(u:bat[:uuid],rev:bat[:lng],js:bat[:json]):json\naddress JSONresultSet\ncomment \"Converts the json store into a single json string:\";\n" }, 
