/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "language", "\nmodule language;\n\npattern call(s:str):void\naddress CMDcallString\n;\npattern call(m:str,f:str):void\naddress CMDcallFunction;\npattern call(s:bat[:str]):void\naddress CMDcallBAT\n;\npattern source(f:str):void\naddress CMDevalFile\n;\n\nunsafe command raise(msg:str) :str \naddress CMDraise\n;\nunsafe command assert(v:bit,term:str):void\naddress MALassertBit;\nunsafe command assert(v:sht,term:str):void\naddress MALassertSht;\nunsafe command assert(v:int,term:str):void\naddress MALassertInt;\nunsafe command assert(v:lng,term:str):void\naddress MALassertLng;\nunsafe command assert(v:str,term:str):void\naddress MALassertStr;\nunsafe command assert(v:oid,term:str):void\naddress MALassertOid;\nunsafe pattern assert(v:any_1,pname:str,oper:str,val:any_2):void\naddress MALassertTriple\n;\n\npattern dataflow():bit\naddress MALstartDataflow\n;\n\npattern sink(v:any...):void\naddress MALgarbagesink\n;\n\npattern pass(v:any_1)\naddress MALpass\n;\n\npattern block(v:int,w:any...):int\naddress deblockdataflow\n;\n\npattern register(m:str,f:str,code:str,help:str):void\naddress CMDregisterFunction\ncomment\"Compile the code string to MAL and register it as a function.\";" }, 
