/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "mal_io", "\nmodule io;\npattern stdin():bstream\naddress io_stdin\n;\npattern stderr():streams\naddress io_stderr\n;\npattern stdout():streams\naddress io_stdout\n;\n\npattern print(val:any_1,lst:any...):void \naddress IOprint_val\n;\n\npattern print(b1:bat[:any]...):void \naddress IOtable\n;\n\npattern print(val:any_1):void \naddress IOprint_val\n;\npattern print(val:bat[:any_1]):void \naddress IOprint_val\n;\n\npattern printf(fmt:str,val:any...):void \naddress IOprintf\n;\npattern printf(fmt:str):void \naddress IOprintf\n;\n\npattern printf(filep:streams,fmt:str,val:any...):void \naddress IOprintfStream\n;\npattern printf(filep:streams,fmt:str):void \naddress IOprintfStream\n;\n\ncommand export(b:bat[:any_2], filepath:str)  \naddress IOexport\n;\n\ncommand import(b:bat[:any_2], filepath:str)\naddress IOimport\n;\n\ncommand setmallocsuccesscount(count:lng):void\naddress IOsetmallocsuccesscount\n;" }, 
