/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "mat", "\nmodule mat;\n\npattern new(b:bat[:any_2]...):bat[:any_2]\naddress MATpack\ncomment \"Define a Merge Association Table (MAT). Fall back to the pack operation\nwhen this is called \";\n\npattern pack(:any_2...):bat[:any_2]\naddress MATpackValues\ncomment \"Materialize the MAT (of values) into a BAT\";\n\npattern pack(b:bat[:any_2]...):bat[:any_2]\naddress MATpack\ncomment \"Materialize the MAT into a BAT\";\n\npattern packIncrement(b:bat[:any_2],pieces:int):bat[:any_2]\naddress MATpackIncrement\ncomment \"Prepare incremental mat pack\";\n\npattern packIncrement(b:bat[:any_2],c:bat[:any_2]):bat[:any_2]\naddress MATpackIncrement\ncomment \"Prepare incremental mat pack\";" }, 
