/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "mat", "\nmodule mat;\n\npattern new(b:bat[:any_2]...):bat[:any_2]\naddress MATpack\n;\n\npattern pack(:any_2...):bat[:any_2]\naddress MATpackValues\n;\n\npattern pack(b:bat[:any_2]...):bat[:any_2]\naddress MATpack\n;\n\npattern packIncrement(b:bat[:any_2],pieces:int):bat[:any_2]\naddress MATpackIncrement\n;\n\npattern packIncrement(b:bat[:any_2],c:bat[:any_2]):bat[:any_2]\naddress MATpackIncrement\n;" }, 
