/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "mdb", "\nmodule mdb;\n\npattern start():void \naddress MDBstart\n;\npattern start(clientid:int):void \naddress MDBstart\n;\npattern start(mod:str,fcn:str):void \naddress MDBstartFactory\n;\n\npattern stop():void\naddress MDBstop\n;\n\npattern inspect(mod:str,fcn:str):void\naddress MDBinspect\n;\n\ncommand modules():bat[:str] \naddress CMDmodules\n;\n\npattern setTrace(b:bit):void\naddress MDBsetTrace\n;\n\npattern setTrace(b:str):void\naddress MDBsetVarTrace\n;\n\npattern setCatch(b:bit):void\naddress MDBsetCatch\n;\n\ncommand getDebug():int\naddress MDBgetDebug\n;\n\ncommand setDebug(flg:str):int\naddress MDBsetDebugStr\n;\ncommand setDebug(flg:int):int\naddress MDBsetDebug\n;\n\ncommand getException(s:str):str\naddress MDBgetExceptionVariable\n;\ncommand getReason(s:str):str\naddress MDBgetExceptionReason\n;\ncommand getContext(s:str):str\naddress MDBgetExceptionContext\n;\n\npattern list():void\naddress MDBlist\n;\npattern listMapi():void\naddress MDBlistMapi\n;\npattern list(M:str,F:str):void\naddress MDBlist3\n;\npattern List():void \naddress MDBlistDetail\n;\npattern List(M:str,F:str):void \naddress MDBlist3Detail\n;\npattern var():void \naddress MDBvar\n;\npattern var(M:str,F:str):void \naddress MDBvar3\n;\n\npattern getStackDepth():int \naddress MDBStkDepth\n;\n\npattern getStackFrame(i:int)(:bat[:str] ,:bat[:str])\naddress MDBgetStackFrameN;\npattern getStackFrame()(:bat[:str] ,:bat[:str])\naddress MDBgetStackFrame\n;\npattern getStackTrace()(:bat[:int], :bat[:str])\naddress MDBStkTrace;\n\npattern dump()\naddress MDBdump\n;\n\npattern getDefinition():bat[:str] \naddress MDBgetDefinition\n;" }, 
