/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "oltp", "\n\nmodule oltp;\n\nunsafe pattern init()\naddress OLTPinit\n;\n\nunsafe pattern enable()\naddress OLTPenable\n;\n\nunsafe pattern disable()\naddress OLTPdisable\n;\n\nunsafe pattern reset()\naddress OLTPreset\n;\n\nunsafe pattern lock(lck:int...):void\naddress OLTPlock\n;\n\nunsafe pattern release(lck:int...):void\naddress OLTPrelease\n;\n\nunsafe pattern table() (start:bat[:timestamp], usr:bat[:str], unit:bat[:int], cnt:bat[:int])\naddress OLTPtable\n;\n\nunsafe command isenabled():int\naddress OLTPis_enabled\n;" }, 
