/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "oltp", "\n\nmodule oltp;\n\nunsafe pattern init()\naddress OLTPinit\ncomment \"Initialize the lock table\";\n\nunsafe pattern enable()\naddress OLTPenable\ncomment \"Enable the OLTP delay monitor\";\n\nunsafe pattern disable()\naddress OLTPdisable\ncomment \"Disable the OLTP delay monitor\";\n\nunsafe pattern reset()\naddress OLTPreset\ncomment \"Reset the OLTP lock table\";\n\nunsafe pattern lock(lck:int...):void\naddress OLTPlock\ncomment \"Wait for all write locks needed\";\n\nunsafe pattern release(lck:int...):void\naddress OLTPrelease\ncomment \"Release for all write locks needed\";\n\nunsafe pattern table() (start:bat[:timestamp], usr:bat[:str], unit:bat[:int], cnt:bat[:int])\naddress OLTPtable\ncomment \"Show status of lock table\";\n\nunsafe command isenabled():int\naddress OLTPis_enabled\ncomment \"Query the OLTP state\";" }, 
