/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "profiler", "\nmodule profiler;\n\npattern start()\naddress CMDstartProfiler\n;\n\npattern stop():void\naddress CMDstopProfiler\n;\n\ncommand starttrace()\naddress CMDstartTrace\n;\n\ncommand starttrace(path:str)\naddress CMDstartTracePath\n;\n\ncommand stoptrace():void\naddress CMDstopTrace\n;\n\ncommand stoptrace(path:str):void\naddress CMDstopTracePath\n;\n\ncommand setheartbeat(b:int):void\naddress CMDsetHeartbeat\n;\n\ncommand getlimit():int\naddress CMDgetprofilerlimit\n;\n\ncommand setlimit(i:int)\naddress CMDsetprofilerlimit\n;\n\npattern openstream(mode:int):void\naddress CMDopenProfilerStream\n;\n\ncommand closestream():void\naddress CMDcloseProfilerStream\n;\n\ncommand noop():void\naddress CMDnoopProfiler\n;\n\ncommand getTrace(e:str):bat[:any_1]\naddress CMDgetTrace\n;\n\ncommand cleanup():void\naddress CMDcleanupTraces\n;\n\ncommand getDiskReads():lng\naddress CMDgetDiskReads\n;\ncommand getDiskWrites():lng\naddress CMDgetDiskWrites\n;\n\ncommand getUserTime():lng\naddress CMDgetUserTime\n;\ncommand getSystemTime():lng\naddress CMDgetSystemTime\n;\n\ncommand cpustats()(user:lng, nice:lng, sys:lng,idle:lng,iowait:lng)\naddress CMDcpustats\n;\n\ncommand cpuload(user:lng, nice:lng, sys:lng,idle:lng,iowait:lng)(cycles:int,io:int)\naddress CMDcpuloadPercentage\n;" }, 
