/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "querylog", "\nmodule querylog;\n\ncommand enable(threshold:int)\naddress QLOGenableThreshold\ncomment \"Turn on the query logger\";\n\ncommand enable()\naddress QLOGenable\ncomment \"Turn on the query logger\";\n\ncommand disable()\naddress QLOGdisable\ncomment \"Turn off the query logger\";\n\ncommand isset():int\naddress QLOGissetFcn\ncomment \"Return status of query logger\";\n\ncommand empty()\naddress QLOGempty\ncomment \"Clear the query log tables\";\n\npattern append(q:str, pipe:str, usr:str, tick:timestamp)\naddress QLOGappend\ncomment \"Add a new query call to the query log\";\n\ncommand define(q:str, pipe:str, size:int)\naddress QLOGdefineNaive\ncomment \"Noop operation, just marking the query\";\n\npattern call(tick1:timestamp, tick2:timestamp, arg:str, tuples:lng, xtime:lng, rtime:lng, cpu:int, iowait:int)\naddress QLOGcall\ncomment \"Add a new query call to the query log\";" }, 
