/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "remote", "\nmodule remote;\n\ncommand prelude():void\naddress RMTprelude\n;\n\ncommand epilogue():void\naddress RMTepilogue\n;\n\ncommand resolve(pattern:str):bat[:str]\naddress RMTresolve\n;\n\ncommand connect(uri:str, user:str, passwd:str):str\naddress RMTconnect\n;\ncommand connect(uri:str, user:str, passwd:str, scen:str):str\naddress RMTconnectScen\n;\npattern connect(table:str, schen:str):str\naddress RMTconnectTable\n;\n\ncommand disconnect(conn:str):void\naddress RMTdisconnect\n;\n\npattern get(conn:str, ident:str):any\naddress RMTget\n;\n\npattern put(conn:str, object:any):str\naddress RMTput\n;\n\npattern register(conn:str, mod:str, fcn:str):void\naddress RMTregister\n;\n\npattern exec(conn:str, mod:str, func:str):str\naddress RMTexec\n;\npattern exec(conn:str, mod:str, func:str):str...\naddress RMTexec\n;\npattern exec(conn:str, mod:str, func:str, :str...):str\naddress RMTexec\n;\npattern exec(conn:str, mod:str, func:str, :str...):str...\naddress RMTexec\n;\ncommand isalive(conn:str):int\naddress RMTisalive\n;\n\npattern batload(tt:any_1, size:int):bat[:any_1]\naddress RMTbatload\n;\n\npattern batbincopy(b:bat[:any]):void\naddress RMTbincopyto\n;\npattern batbincopy():bat[:any]\naddress RMTbincopyfrom\n;\n\npattern bintype():void\naddress RMTbintype\n;\n\ncommand register_supervisor(sup_uuid:str, query_uuid:str):int\naddress RMTregisterSupervisor\n;\n\nremote.prelude();" }, 
