/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sabaoth", "\nmodule sabaoth;\n\ncommand prelude() :void\naddress SABprelude\n;\n\ncommand epilogue() :void\naddress SABepilogue\n;\n\n\ncommand marchScenario(lang:str)\naddress SABmarchScenario\n;\n\ncommand retreatScenario(lang:str)\naddress SABretreatScenario\n;\n\ncommand marchConnection(host:str, port:int)\naddress SABmarchConnection\n;\n\ncommand getLocalConnectionURI():str\naddress SABgetLocalConnectionURI\n;\n\ncommand getLocalConnectionHost():str\naddress SABgetLocalConnectionHost\n;\n\ncommand getLocalConnectionPort():int\naddress SABgetLocalConnectionPort\n;" }, 
