/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sabaoth", "\nmodule sabaoth;\n\ncommand prelude() :void\naddress SABprelude\ncomment \"Initialise the sabaoth module\";\n\ncommand epilogue() :void\naddress SABepilogue\ncomment \"Release the resources held by the sabaoth module\";\n\n\ncommand marchScenario(lang:str)\naddress SABmarchScenario\ncomment \"Publishes the given language as available for this server\";\n\ncommand retreatScenario(lang:str)\naddress SABretreatScenario\ncomment \"Unpublishes the given language as available for this server\";\n\ncommand marchConnection(host:str, port:int)\naddress SABmarchConnection\ncomment \"Publishes the given host/port as available for connecting to this server\";\n\ncommand getLocalConnectionURI():str\naddress SABgetLocalConnectionURI\ncomment \"Returns the URI this server can be connected to, or nil if none\";\n\ncommand getLocalConnectionHost():str\naddress SABgetLocalConnectionHost\ncomment \"Returns the hostname this server can be connected to, or nil if none\";\n\ncommand getLocalConnectionPort():int\naddress SABgetLocalConnectionPort\ncomment \"Returns the port this server can be connected to, or 0 if none\";" }, 
