/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sample", "\n\nmodule sample;\n\npattern subuniform(b:bat[:any],sample_size:lng):bat[:oid]\naddress SAMPLEuniform\ncomment \"Returns the oids of a uniform sample of size s\";\n\npattern subuniform(b:bat[:any],sample_size:lng,sample_seed:int):bat[:oid]\naddress SAMPLEuniform\ncomment \"Returns the oids of a uniform sample of size s and where the prg is seeded with sample_seed\";\n\npattern subuniform(b:bat[:any],p:dbl):bat[:oid]\naddress SAMPLEuniform\ncomment \"Returns the oids of a uniform sample of size = (p x count(b)), where 0 <= p <= 1.0\";\n\npattern subuniform(b:bat[:any],p:dbl,sample_seed:int):bat[:oid]\naddress SAMPLEuniform\ncomment \"Returns the oids of a uniform sample of size = (p x count(b)), where 0 <= p <= 1.0 and where the prg is seeded with sample_seed\";" }, 
