/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sysmon", "\nmodule sysmon;\n\npattern pause(id:sht)\naddress SYSMONpause\ncomment \"Suspend a running query\";\npattern pause(id:int)\naddress SYSMONpause\ncomment \"Suspend a running query\";\npattern pause(id:lng)\naddress SYSMONpause\ncomment \"Suspend a running query\";\n\npattern resume(id:sht)\naddress SYSMONresume\ncomment \"Resume processing of a query \";\npattern resume(id:int)\naddress SYSMONresume\ncomment \"Resume processing of a query \";\npattern resume(id:lng)\naddress SYSMONresume\ncomment \"Resume processing of a query \";\n\npattern stop(id:sht)\naddress SYSMONstop\ncomment \"Stop a single query a.s.a.p.\";\npattern stop(id:int)\naddress SYSMONstop\ncomment \"Stop a single query a.s.a.p.\";\npattern stop(id:lng)\naddress SYSMONstop\ncomment \"Stop a single query a.s.a.p.\";\n\npattern queue()(tag:bat[:lng], user:bat[:str],started:bat[:timestamp],estimate:bat[:timestamp],progress:bat[:int], status:bat[:str], qrytag:bat[:oid],query:bat[:str])\naddress SYSMONqueue;" }, 
