/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sysmon", "\nmodule sysmon;\n\npattern pause(id:sht)\naddress SYSMONpause\n;\npattern pause(id:int)\naddress SYSMONpause\n;\npattern pause(id:lng)\naddress SYSMONpause\n;\n\npattern resume(id:sht)\naddress SYSMONresume\n;\npattern resume(id:int)\naddress SYSMONresume\n;\npattern resume(id:lng)\naddress SYSMONresume\n;\n\npattern stop(id:sht)\naddress SYSMONstop\n;\npattern stop(id:int)\naddress SYSMONstop\n;\npattern stop(id:lng)\naddress SYSMONstop\n;\n\npattern queue()(tag:bat[:lng], user:bat[:str],started:bat[:timestamp],estimate:bat[:timestamp],progress:bat[:int], status:bat[:str], qrytag:bat[:oid],query:bat[:str])\naddress SYSMONqueue;" }, 
