/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "tokenizer", "\nmodule tokenizer\ncomment \"The tokenizer provides fast access to a large collection of strings\nbased on a vertical fragmented representation.\";\n\ncommand open(name:str):void\naddress TKNZRopen\ncomment \"open the named tokenizer store, a new one is created if the specified name does not exist\";\n\ncommand close():void\naddress TKNZRclose\ncomment \"close the current tokenizer store\";\n\npattern take(i:oid):str\naddress TKNZRtakeOid\ncomment \"reconstruct and returns the i-th string\";\n\npattern locate(s:str):oid\naddress TKNZRlocate\ncomment \"if the given string is in the store returns its oid, otherwise oid_nil\";\n\ncommand append(u:str):oid\naddress TKNZRappend\ncomment \"tokenize a new string and append it to the tokenizer (duplicate elimination is performed)\";\n\ncommand depositFile(fnme:str):void\naddress TKNZRdepositFile\ncomment \"batch insertion from a file of strings to tokenize, each string is separated by a new line\";\n\ncommand getLevel(i:int):bat[:str]\naddress TKNZRgetLevel\ncomment \"administrative function that returns the bat on level i\";\n\ncommand getIndex():bat[:oid]\naddress TKNZRgetIndex\ncomment \"administrative function that returns the INDEX bat\";\n\ncommand getCount():bat[:lng]\naddress TKNZRgetCount\ncomment \"debugging function that returns the size of the bats at each level\";\n\ncommand getCardinality():bat[:lng]\naddress TKNZRgetCardinality\ncomment \"debugging function that returns the unique tokens at each level\";" }, 
