/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "tokenizer", "\nmodule tokenizer\n;\n\ncommand open(name:str):void\naddress TKNZRopen\n;\n\ncommand close():void\naddress TKNZRclose\n;\n\npattern take(i:oid):str\naddress TKNZRtakeOid\n;\n\npattern locate(s:str):oid\naddress TKNZRlocate\n;\n\ncommand append(u:str):oid\naddress TKNZRappend\n;\n\ncommand depositFile(fnme:str):void\naddress TKNZRdepositFile\n;\n\ncommand getLevel(i:int):bat[:str]\naddress TKNZRgetLevel\n;\n\ncommand getIndex():bat[:oid]\naddress TKNZRgetIndex\n;\n\ncommand getCount():bat[:lng]\naddress TKNZRgetCount\n;\n\ncommand getCardinality():bat[:lng]\naddress TKNZRgetCardinality\n;" }, 
