/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "transaction", "\nmodule transaction;\n\ncommand sync():bit\naddress TRNglobal_sync\ncomment \"Save all persistent BATs\";\ncommand commit():bit\naddress TRNglobal_commit\ncomment \"Global commit on all BATs\";\ncommand abort():bit\naddress TRNglobal_abort\ncomment \"Global abort on all BATs\";\ncommand subcommit(b:bat[:str]):bit\naddress TRNsubcommit\ncomment \"commit only a set of BATnames, passed in the tail\n(to which you must have exclusive access!)\";\n\npattern commit(c:any...)\naddress TRNtrans_commit\ncomment \"Commit changes in certain BATs.\";\npattern abort(c:any...)\naddress TRNtrans_abort\ncomment \"Abort changes in certain BATs.\";\npattern clean(c:any...)\naddress TRNtrans_clean\ncomment \"Declare a BAT clean without flushing to disk.\";" }, 
