/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "transaction", "\nmodule transaction;\n\ncommand sync():bit\naddress TRNglobal_sync\n;\ncommand commit():bit\naddress TRNglobal_commit\n;\ncommand abort():bit\naddress TRNglobal_abort\n;\ncommand subcommit(b:bat[:str]):bit\naddress TRNsubcommit\n;\n\npattern commit(c:any...)\naddress TRNtrans_commit\n;\npattern abort(c:any...)\naddress TRNtrans_abort\n;\npattern clean(c:any...)\naddress TRNtrans_clean\n;" }, 
