/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "txtsim", "\nmodule txtsim;\n\ncommand levenshtein(s:str, t:str, insdel_cost:int, replace_cost:int, transpose_cost:int) : int\naddress levenshtein_impl\n;\n\ncommand levenshtein(s:str, t:str) : int\naddress levenshteinbasic_impl\n;\n\ncommand editdistance(s:str, t:str) : int\naddress levenshteinbasic_impl\n;\n\ncommand editdistance2(s:str, t:str) : int\naddress levenshteinbasic2_impl\n;\n\ncommand similarity(string1:str, string2:str, minimum:dbl) : dbl\naddress fstrcmp_impl\n;\n\ncommand similarity(string1:str, string2:str) : dbl\naddress fstrcmp0_impl\n;\n\ncommand soundex(name:str) : str\naddress soundex_impl\n;\n\ncommand stringdiff(s1:str, s2:str) :int\naddress stringdiff_impl\n;\n\ncommand qgramnormalize(input:str): str\naddress CMDqgramnormalize\n;\n\ncommand qgramselfjoin(qgram:bat[ :oid], id:bat[ :oid], pos:bat[ :int], len:bat[ :int], c:flt, k:int) (:bat[:int],:bat[ :int])\naddress CMDqgramselfjoin\n;\n\ncommand txtsim.str2qgrams(s:str):bat[:str]\naddress CMDstr2qgrams\n;" }, 
