/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "blob", "\nmodule blob;\n\natom blob;\n\ncommand tostr()   address BLOBtostr;\ncommand fromstr() address BLOBfromstr;\ncommand cmp()     address BLOBcmp;\ncommand hash()    address BLOBhash;\ncommand null()    address BLOBnull;\ncommand read()    address BLOBread;\ncommand write()   address BLOBwrite;\ncommand put()     address BLOBput;\ncommand del()     address BLOBdel;\ncommand length()  address BLOBlength;\ncommand heap()    address BLOBheap;\n\ncommand blob(s:blob):blob\naddress BLOBblob_blob\ncomment \"Noop routine.\";\n\ncommand blob(s:str):blob\naddress BLOBblob_fromstr;\n\ncommand toblob(v:str) :blob\naddress BLOBtoblob\ncomment \"store a string as a blob.\";\ncommand nitems(b:blob):int\naddress BLOBnitems\ncomment \"get the number of bytes in this blob.\";\n\ncommand prelude() :void\naddress BLOBprelude;\n\nblob.prelude();\n\nmodule calc;\n\ncommand blob(b:blob):blob address BLOBblob_blob;\ncommand blob(s:str):blob address BLOBblob_fromstr;" }, 
