/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "streams", "\nmodule streams;\n\natom streams:ptr;\n\nunsafe command openReadBytes( filename:str ) :streams\naddress mnstr_open_rstreamwrap\n;\nunsafe command openWriteBytes( filename:str ) :streams\naddress mnstr_open_wstreamwrap\n;\n\nunsafe command openRead( filename:str ) :streams\naddress mnstr_open_rastreamwrap\n;\nunsafe command openWrite( filename:str ) :streams\naddress mnstr_open_wastreamwrap\n;\n\nunsafe command blocked( s:streams ) :streams\naddress open_block_streamwrap\n;\n\nunsafe command writeStr( s:streams, data:str ):void\naddress mnstr_write_stringwrap\n;\nunsafe command writeInt( s:streams, data:int ):void\naddress mnstr_writeIntwrap\n;\nunsafe command readStr( s:streams):str\naddress mnstr_read_stringwrap\n;\nunsafe command readInt( s:streams):int\naddress mnstr_readIntwrap\n;\n\nunsafe command flush( s:streams )\naddress mnstr_flush_streamwrap\n;\n\nunsafe command close( s:streams )\naddress mnstr_close_streamwrap\n;\n\natom bstream:ptr;\nunsafe command create(s:streams, bufsize:int):bstream\naddress bstream_create_wrapwrap\n;\n\nunsafe command destroy(s:bstream)\naddress bstream_destroy_wrapwrap\n;\n\nunsafe command read(s:bstream,size:int):int\naddress bstream_read_wrapwrap\n;" }, 
