/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "url", "\nmodule url;\n\natom url:str;\n\ncommand url(s:str) :url\naddress URLnew\n;\n\ncommand url(s:url) :url\naddress URLnoop\n;\n\ncommand calc.url(s:str) :url\naddress URLnew\n;\n\ncommand calc.url(s:url) :url\naddress URLnoop\n;\n\ncommand getAnchor(u:url) :str\naddress URLgetAnchor\n;\n\ncommand getBasename(u:url) :str\naddress URLgetBasename\n;\n\ncommand getContent(u:url) :str\naddress URLgetContent\n;\n\ncommand getContext(u:url) :str\naddress URLgetContext\n;\n\n\ncommand getDomain(u:url) :str\naddress URLgetDomain\n;\n\ncommand getExtension(u:url) :str\naddress URLgetExtension\n;\n\ncommand getFile(u:url) :str\naddress URLgetFile\n;\n\ncommand getHost(u:url) :str\naddress URLgetHost\n;\n\ncommand getPort(u:url) :str\naddress URLgetPort\n;\n\ncommand getProtocol(u:url) :str\naddress URLgetProtocol\n;\n\ncommand getQuery(u:url) :str\naddress URLgetQuery\n;\n\ncommand getUser(u:url) :str\naddress URLgetUser\n;\n\ncommand getRobotURL(u:url) :str\naddress URLgetRobotURL\n;\n\ncommand isaURL(u:url) :bit\naddress URLisaURL\n;\n\ncommand new(p:str, h:str, prt:int, f:str) :url\naddress URLnew4\n;\n\ncommand new(prot:str, host:str, fnme:str) :url\naddress URLnew3\n;\n\ncommand fromstr()\naddress URLfromString\n;\n\ncommand tostr()\naddress URLtoString\n;" }, 
