/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "xml", "\natom xml :str;\n\ncommand fromstr()\naddress XMLfromString\n;\n\ncommand tostr()\naddress XMLtoString\n;\n\ncommand xml(src:str):xml\naddress XMLstr2xml\n;\n\ncommand str(src:xml):str\naddress XMLxml2str\n;\n\ncommand text(src:xml):str\naddress XMLxmltext\n;\n\ncommand comment(val:str):xml\naddress XMLcomment\n;\n\ncommand parse(doccont:str,val:str,option:str):xml\naddress XMLparse\n;\n\ncommand pi(target:str,val:str):xml\naddress XMLpi\n;\n\ncommand document(val:str):xml\naddress XMLdocument\n;\n\ncommand content(val:str):xml\naddress XMLcontent\n;\n\ncommand root(val:xml, version:str, standalone:str):xml\naddress XMLroot\n;\n\ncommand attribute(name:str, val:str):xml\naddress XMLattribute\n;\n\ncommand element(name:str, ns:xml, attr:xml, s:xml) :xml\naddress XMLelement\n;\n\ncommand element(name:str, s:xml) :xml\naddress XMLelementSmall\n;\n\ncommand concat(val1:xml, val2:xml):xml\naddress XMLconcat\n;\n\npattern forest(val:xml...):xml\naddress XMLforest\n;\n\ncommand isdocument(val:str):bit\naddress XMLisdocument\n;\n\ncommand prelude() :void\naddress XMLprelude;\n\nxml.prelude();\n\nmodule calc;\ncommand xml(src:str):xml address XMLstr2xml;\ncommand xml(src:xml):xml address XMLxml2xml;\n\n" }, 
