
START TRANSACTION;

CREATE TABLE vals(id DOUBLE, type INTEGER);

INSERT INTO vals VALUES (1, 100), (0, 50);

plan SELECT type FROM vals GROUP BY type SAMPLE 1 USING WEIGHTS id;
SELECT type FROM vals GROUP BY type SAMPLE 1 USING WEIGHTS id;

ROLLBACK;

