
START TRANSACTION;

CREATE TABLE vals(id DOUBLE, type INTEGER);

INSERT INTO vals VALUES (1, 100), (0, 50);

SELECT type, COUNT(*) FROM vals GROUP BY type SAMPLE 1 USING WEIGHTS cast(id AS double);

ROLLBACK;

