/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sql_transaction", "\nmodule sql;\n\npattern transaction_release(chain:int,name:str):void\naddress SQLtransaction_release\n;\n\npattern transaction_commit(chain:int,name:str):void\naddress SQLtransaction_commit\n;\n\npattern transaction_rollback(chain:int,name:str):void\naddress SQLtransaction_rollback\n;\n\npattern transaction_begin(chain:int,name:str):void\naddress SQLtransaction_begin\n;\n\nunsafe pattern transaction()\naddress SQLtransaction2\n;\n" }, 
