/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "sql_inspect", "\nmodule sql;\n\ninline function sql_environment()(name:bat[:str],value:bat[:str]);\n\t(name,value):= inspect.getEnvironment();\n\treturn (name,value) := (name,value);\nend sql_environment;" }, 
