/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "udf", "\nmodule udf;\n\ncommand reverse(ra1:str):str\naddress UDFreverse\ncomment \"Reverse a string\";\n\n\nmodule batudf;\n\ncommand reverse(b:bat[:str]):bat[:str]\naddress UDFBATreverse\ncomment \"Reverse a BAT of strings\";\n\n\n\nmodule udf;\n\ncommand fuse(one:bte,two:bte):sht\naddress UDFfuse_bte_sht\ncomment \"fuse two (1-byte) bte values into one (2-byte) sht value\";\n\ncommand fuse(one:sht,two:sht):int\naddress UDFfuse_sht_int\ncomment \"fuse two (2-byte) sht values into one (4-byte) int value\";\n\ncommand fuse(one:int,two:int):lng\naddress UDFfuse_int_lng\ncomment \"fuse two (4-byte) int values into one (8-byte) lng value\";\n\n\nmodule batudf;\n\ncommand fuse(one:bat[:bte],two:bat[:bte]):bat[:sht]\naddress UDFBATfuse\ncomment \"fuse two (1-byte) bte values into one (2-byte) sht value\";\n\ncommand fuse(one:bat[:sht],two:bat[:sht]):bat[:int]\naddress UDFBATfuse\ncomment \"fuse two (2-byte) sht values into one (4-byte) int value\";\n\ncommand fuse(one:bat[:int],two:bat[:int]):bat[:lng]\naddress UDFBATfuse\ncomment \"fuse two (4-byte) int values into one (8-byte) lng value\";" }, 
