/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "udf_hge", "\nmodule udf;\n\ncommand fuse(one:lng,two:lng):hge\naddress UDFfuse_lng_hge\ncomment \"fuse two (8-byte) lng values into one (16-byte) hge value\";\n\n\nmodule batudf;\n\ncommand fuse(one:bat[:lng],two:bat[:lng]):bat[:hge]\naddress UDFBATfuse\ncomment \"fuse two (8-byte) lng values into one (16-byte) hge value\";" }, 
