# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = .. \
	 ../../../include \
	../../../common \
	../../../storage \
	../../../server \
	../../../../monetdb5/modules/atoms \
	../../../../monetdb5/modules/kernel \
	../../../../monetdb5/mal \
	../../../../monetdb5/modules/mal \
	../../../../monetdb5/optimizer \
	../../../../common/options \
	../../../../common/stream \
	../../../../gdk

lib__sample = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = sample.c sample.h sample_impl.h
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		   ../../../../gdk/libbat
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 80_sample.sql
}

EXTRA_DIST_DIR = Tests

