# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2012 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../modules/atoms \
		   ../../modules/kernel \
		   ../../mal \
		   ../../optimizer \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../gdk

MTSAFE

lib_crackers = {
	MODULE
	DIR = libdir/monetdb5
	SEP = _
	SOURCES = crackers.mx \
			  crackers_AVL_index.mx \
			  crackers_AVL_tree.mx \
			  crackers_index.mx \
			  crackers_core_unordered.mx \
			  crackers_select_ops.mx \
			  crackers_holistic.c \
			  crackers_holistic.h \
			  crackers_selectst_ops.mx \
			  crackers_selecthol_ops.mx \
			  opt_selcrack.mx \
			  opt_selcrackst.mx \
			  opt_selcrackhol.mx 
	LIBS = ../../tools/libmonetdb5 \
		   ../../../gdk/libbat \
		   ../../../common/stream/libstream \
		   ../../../common/utils/libmutils \
		   $(MALLOC_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = crackers.mx \
			  opt_selcrack.mx \
			  opt_selcrackst.mx \
			  opt_selcrackhol.mx \
			  crackers_holistic.mal
}

headers_crackersautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 60_crackers.mal
}

EXTRA_DIST = 60_crackers.mal

EXTRA_DIST_DIR = Tests
