#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.

import sys

# Create cheader.text.h
CAPIHeaderOriginal = open(sys.argv[1], 'r')
CAPIHeaderText = open(sys.argv[2], 'w+')
CAPIHeaderText.write("// This file was generated automatically through cmake.\n// Do not edit this file directly.\n")
CAPIHeaderText.write('const char* cheader_header_text = \n')
for line in CAPIHeaderOriginal:
    if len(line.strip()) > 0:
        CAPIHeaderText.write('"' + line.replace("\n", "").replace('"', '\\"').replace('\\', '\\\\') + '\\n"\n')
CAPIHeaderText.write(";\n")
CAPIHeaderOriginal.close()
CAPIHeaderText.close()
