/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "capi", "\nmodule capi;\n\npattern eval(fptr:ptr,cpp:bit,expr:str):any\naddress CUDFevalStd\ncomment \"Execute a simple CUDF script returning a single value\";\n\npattern eval(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalStd\ncomment \"Execute a simple CUDF script value\";\n\npattern subeval_aggr(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalAggr\ncomment \"grouped aggregates through CUDF\";\n\npattern eval_aggr(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalAggr\ncomment \"grouped aggregates through CUDF\";\n\ncommand prelude() :void address CUDFprelude;\ncapi.prelude();\n\nmodule batcapi;\n\npattern eval(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalStd\ncomment \"Execute a simple CUDF script value\";\n\npattern subeval_aggr(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalAggr\ncomment \"grouped aggregates through CUDF\";\n\npattern eval_aggr(fptr:ptr,cpp:bit,expr:str,arg:any...):any...\naddress CUDFevalAggr\ncomment \"grouped aggregates through CUDF\";" }, 
