# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

sed '/^$/q' $0			# copy copyright from this file

cat <<EOF
# This file was generated by using the script ${0##*/}.

module grid;

EOF

integer="bte sht int lng"	# all integer types
numeric="$integer flt dbl"	# all numeric types

name="distance"
for tp1 in $numeric; do
	for tp2 in $numeric; do
	    cat <<EOF
pattern ${name}(x1:${tp1}, y1:${tp1}, x2:${tp2}, y2:${tp2}, d:dbl) :bit
address GRID${name}
comment "Return true when the cartesian ${name} between two points is less than the specified ${name}";
command ${name}subselect(x1:bat[:${tp1}], y1:bat[:${tp1}], cand1:bat[:oid], x2:${tp2}, y2:${tp2}, d:dbl, anti:bit):bat[:oid]
address GRID${name}subselect_${tp1}_${tp2}
comment "Return the OIDs of points that are close to the specified point";
pattern ${name}subjoin(x1:bat[:${tp1}], y1:bat[:${tp1}], x2:bat[:${tp2}], y2:bat[:${tp2}], d:dbl, s1:bat[:oid], s2:bat[:oid], nil_matches:bit, estimate:lng)(r1:bat[:oid],r2:bat[:oid])
address GRID${name}subjoin
comment "Returns the point pairs that with ${name} less than the specified ${name}";

EOF
	done
done
echo
