# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

MTSAFE
INCLUDES = ../lib \
           ../../gdk \
           ../../common/stream \
           ../../common/options \
           ../../monetdb5/mal \
           $(GEOS_INCS) $(PROJ_INCS)

lib__geom = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = geom.h geom.c geomBulk.c geom_upgrade.c grid.h grid_impl.h grid.c
	LIBS = ../lib/libgeom \
		   ../../gdk/libbat \
	       ../../common/stream/libstream \
	       ../../monetdb5/tools/libmonetdb5 \
	       $(GEOS_LIBS) $(PROJ_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = geom.mal
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 30_geom.mal
}

headers_mal_grid = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = grid.mal
}

headers_autoload_grid = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 31_grid.mal
}

headers_mal_grid_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = grid_hge.mal
}

headers_autoload_grid_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 31_grid_hge.mal
}

EXTRA_DIST = 30_geom.mal geom.mal 31_grid.mal grid.mal
