# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2015 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../modules/atoms ../../modules/mal ../../mal \
		   ../../modules/kernel \
		   ../../../clients/mapilib \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   ../../../sql/include \
		   ../../../sql/backends/monet5 \
		   ../../../sql/server \
		   ../../../sql/common \
		   ../../../sql/storage \
		   $(raptor_CFLAGS)

MTSAFE

SUBDIRS = hashmap trie common

lib__rdf = {
	#MODULE
	NOINST
	#DIR = libdir/monetdb5
	SOURCES = rdf.h rdfcommon.h rdfcommon.c rdftypes.h rdfparams.h rdfparams.c rdfschema.h rdfgraph.h rdfgraph.c rdfminheap.h rdfminheap.c rdflabels.h rdfretrieval.h rdfparser.h rdftypes.c rdfparser.c rdfontologyload.h rdfontologyload.c rdf_shredder.c rdfalgebra.c rdfschema.c rdflabels.c rdfretrieval.c rdfscan.h rdfscan.c rdfdump.h rdfdump.c

	#SEP = _
	# LIBS =  ./hashmap/librdfhash 	
	#	../../tools/libmonetdb5 \
	#	   ../../../gdk/libbat \
	#	   $(MALLOC_LIBS) $(raptor_LIBS)
}

headers_rdf_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = rdfalgebra.mal rdfschema.mal rdfoperator.mal
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 50_rdf.mal
}

EXTRA_DIST_DIR = hashmap trie common
EXTRA_DIST = 50_rdf.mal rdfalgebra.mal rdfschema.mal
