/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "generator_hge", "\nmodule generator;\n\npattern series(first:hge,limit:hge):bat[:hge]\naddress VLTgenerator_table;\n\npattern series(first:hge,limit:hge,step:hge):bat[:hge]\naddress VLTgenerator_table\n;\n\npattern parameters(first:hge,limit:hge,step:hge):bat[:hge]\naddress VLTgenerator_noop\n;\n\npattern parameters(first:hge,limit:hge):bat[:hge]\naddress VLTgenerator_noop;\n\npattern thetaselect(b:bat[:hge], low:hge, oper:str) :bat[:oid]\naddress VLTgenerator_thetasubselect\n;\n\npattern thetaselect(b:bat[:hge], cnd:bat[:oid], low:hge, oper:str) :bat[:oid]\naddress VLTgenerator_thetasubselect\n;\n\npattern select(b:bat[:hge], low:hge, high:hge, li:bit, hi:bit, anti:bit) :bat[:oid]\naddress VLTgenerator_subselect\n;\n\npattern select(b:bat[:hge], cand:bat[:oid], low:hge, high:hge, li:bit, hi:bit, anti:bit) :bat[:oid]\naddress VLTgenerator_subselect\n;\n\npattern projection(b:bat[:oid], cand:bat[:hge]) :bat[:hge]\naddress VLTgenerator_projection\n;\n\npattern join(b:bat[:hge], gen:bat[:hge]) (l:bat[:oid],r:bat[:oid])\naddress VLTgenerator_join\n;" }, 
