# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2015 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../../monetdb5/extras/pyapi \
		   ../../monetdb5/mal \
		   ../../monetdb5/modules/atoms \ 
		   ../../monetdb5/modules/mal \ 
		   ../../gdk \
		   ../../common/stream \
		   ../../common/utils \
		   ../../common/options \
		   ../../clients/mapilib \
		   ../../sql/include \
		   ../../sql/server \
		   ../../sql/common \
		   ../../sql/storage \
		   ../../sql/backends/monet5 \ 
		   $(libpy_CFLAGS) \
		   $(pcre_CFLAGS) \

lib_pyembedded  =  {
	SOURCES = embeddedpy.c embeddedpy.h
	VERSION = 1
	LIBS = ../../monetdb5/tools/libmonetdb5 \
		../../gdk/libbat \
		../../monetdb5/extras/pyapi/lib_pyapi \
		../../sql/backends/monet5/lib_sql  \
		$(pcre_LIBS) $(PSAPILIB) \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}
