/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically with mal2h.py. Do not edit this file directly.
{ "run_memo", "\nmodule scheduler;\npattern scheduler.choice():void\naddress RUNchoice\n;\npattern scheduler.choice(arg:any...):void\naddress RUNchoice\n;\n\npattern scheduler.pick(arg:any_1...):any_1\naddress RUNpickResult\n;\n\npattern scheduler.volumeCost(a:any):lng\naddress RUNvolumeCost\n;\n\npattern scheduler.costPrediction(a:any):lng\naddress RUNcostPrediction\n;" }, 
