# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2013 MonetDB B.V.
# All Rights Reserved.

INCLUDES = \
	../../optimizer \
	../../mal \
	../../../gdk \
	../../../common/stream \
	../../../common/options \
	$(MSEED_CFLAGS)

MTSAFE

lib_opt_dvf = {
	MODULE
	DIR = libdir/monetdb5
	SEP = _
	SOURCES = opt_dvf.c opt_dvf.h
	LIBS = ../../tools/libmonetdb5 \
		../../../gdk/libbat \
		../../../common/stream/libstream \
		$(MSEED_LIBS) \
		$(MALLOC_LIBS)
}

lib__dvf = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = dvf.c dvf.h
	LIBS = ../../tools/libmonetdb5 \
		../../../gdk/libbat \
		../../../common/stream/libstream \
		$(MSEED_LIBS) \
		$(MALLOC_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = dvf.mal opt_dvf.mal
}

headers_opt_dvf_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 92_opt_dvf.mal
}

headers_dvf_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 91_dvf.mal
}

EXTRA_DIST = 92_opt_dvf.mal dvf.mal 91_dvf.mal dvf.h

EXTRA_DIST_DIR = Tests
