/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_monetdb_embedded_MonetDBEmbedded */

#ifndef _Included_org_monetdb_embedded_MonetDBEmbedded
#define _Included_org_monetdb_embedded_MonetDBEmbedded
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_monetdb_embedded_MonetDBEmbedded
 * Method:    startupNative
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jboolean JNICALL Java_org_monetdb_embedded_MonetDBEmbedded_startupWrapper
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     org_monetdb_embedded_MonetDBEmbedded
 * Method:    query
 * Signature: (Ljava/lang/String;)Lorg/monetdb/embedded/result/EmbeddedQueryResult;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_embedded_MonetDBEmbedded_queryWrapper
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
