/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_monetdb_embedded_MonetDBEmbedded */

#ifndef _Included_org_monetdb_embedded_MonetDBEmbedded
#define _Included_org_monetdb_embedded_MonetDBEmbedded
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_monetdb_embedded_MonetDBEmbedded
 * Method:    startupWrapper
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_monetdb_embedded_MonetDBEmbedded_startupWrapper
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_monetdb_embedded_MonetDBEmbedded
 * Method:    queryWrapper
 * Signature: (Ljava/lang/String;)Lorg/monetdb/embedded/result/EmbeddedQueryResult;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_embedded_MonetDBEmbedded_queryWrapper
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_monetdb_embedded_MonetDBEmbedded
 * Method:    shutdownWrapper
 * Signature: (V)V;
 */
JNIEXPORT void JNICALL Java_org_monetdb_embedded_MonetDBEmbedded_shutdownWrapper
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
